### ISSUE TITLE
Unable to Run Examples

### ISSUE THREAD

**Issue by brenak** [mbientlab/Warble.NET#1]
Taking this as it is in master, building, then attempting to run either Connect or LeScan fails  on line 48 of Gatt.cs with the following exception:

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unable to load DLL 'warble': The specified module could not be found. (Exception from HRESULT: 0x8007007E))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MbientLab.Warble.Example.Connect.Main(String[] args) in C:\Users\brian\Documents\GitHub\Warble.NET\Example.Connect\Connect.cs:line 7

Inner Exception 1:
{System.DllNotFoundException: Unable to load DLL 'warble': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MbientLab.Warble.Bindings.warble_gatt_create_with_options(Int32 length, Option[] options)
   at MbientLab.Warble.Gatt..ctor(String mac, String hci, String addrType) in C:\Users\brian\Documents\GitHub\Warble.NET\Warble.NetStandard\Gatt.cs:line 48
   at MbientLab.Warble.Example.Connect.<MainAsync>d__1.MoveNext() in C:\Users\brian\Documents\GitHub\Warble.NET\Example.Connect\Connect.cs:line 11}

Looking to get my first successful connection to MetaMotionR device.  Any help would be appreciated.

**Comment by brenak** [comment]
I've installed the package (MetaWear-SDK-CSharp-Plugin-NetStandard) from NuGet, and have received the same error running the examples.  This is why I came to the Warble.Net one directly to see if that just works.

**Comment by scaryghost** [comment]
What platform are you running Warble on?

**Comment by brenak** [comment]
Not the ARM version.  Let me try the windows 10 plugin.  I thought I had already with the same results.  Seemed not matter which version I tried, I go the same error.
